[build]
  publish = "crates/wasm/site"
  # https://advent2019.fornwall.net/.netlify/functions/solve, see ./post-input-netlify
  functions = "crates/wasm/functions/"
  command = "make netlify"

[[redirects]]
  from = "/solve/*"
  to = "/.netlify/functions/solve"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
  for = "/cached-*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
