name: Fuzz testing

on: push

jobs:

  check-seed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - name: Check seed
      run: cd crates/fuzzing-afl && timeout 900s ./check-seed.sh
      continue-on-error: true

  fuzz-afl:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - name: Install current LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Fuzz with AFL
      run: LLVM_CONFIG=llvm-config-11 AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1 AFL_BENCH_UNTIL_CRASH=1 make fuzz-afl
    - name: Upload crashes found by fuzzing
      uses: actions/upload-artifact@v2
      with:
        path: ./crates/fuzzing-afl/target/fuzz-findings/crashes
        name: fuzzing-crashes-afl

  fuzz-libfuzzer:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: nightly-2020-11-21
    - name: Install current LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: Fuzz with libfuzzer
      run: timeout 1800s make fuzz-libfuzzer
      continue-on-error: true
    - name: Upload crashes found by fuzzing
      uses: actions/upload-artifact@v2
      with:
        path: crates/fuzzing-libfuzzer/fuzz/artifacts/fuzz_target/
        name: fuzzing-crashes-libfuzzer

  fuzz-honggfuzz:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v2
    - uses: hecrj/setup-rust-action@v1
    - name: Install honggfuzz dependencies
      run: sudo apt-get -y install build-essential binutils-dev libunwind-dev libblocksruntime-dev liblzma-dev
    - name: Fuzz with honggfuzz
      run: timeout 1800s make fuzz-hfuzz
      continue-on-error: true
      env:
        HFUZZ_RUN_ARGS: "-t 10 --exit_upon_crash"
    - name: Upload crashes found by fuzzing
      uses: actions/upload-artifact@v2
      with:
        path: crates/fuzzing-hfuzz/hfuzz_workspace/advent-of-code-fuzzing-hfuzz/*.fuzz
        name: fuzzing-crashes-honggfuzz
